### ISSUE TITLE
use scss variables across scss files

### ISSUE THREAD

**Issue by codeofsumit** [newtriks/generator-react-webpack#198]
so I started my first component:

```
require('styles/Branding.scss');
require('styles/Cart.scss');

import React from 'react';

class Cart extends React.Component {
    render() {
        return (
            <div className="cart">
                Cart
            </div>
        );
    }
}

Cart.defaultProps = {
};

export default Cart;
```

`Branding.scss` has a lot of variables that I'd like to use inside `Cart.scss`.
How do I make `Branding.scss` globally available in all components? Preferably without `require`ing them inside each one.

(Sorry I'm a React/Webpack beginner, coming from Angular, Gulp and stuff)

**Comment by weblogixx** [comment]
Hi @codeofsumit,

I dont know a way to make it available globally. You could add an alias to the webpack config to require this one in your scss, then it would be a one liner.

I will have a look at this, maybe we could include such a feature.

**Comment by codeofsumit** [comment]
so all css files have their own scope? If I require two css files in one line, I can't use sass variables or anything from one file to the other?

**Comment by weblogixx** [comment]
Hi @codeofsumit,

I am not an expert in sass, but this should be the case, yes. I mainly use it with less, there you are able to do something like:

```css
/* vars.less */
@myMainColor: #f00;

/* some other file, wanting to use myMainColor */
@import '../path/to/vars.less';
body {
  background: @myMainColor;
}
```

There is no global scoping as far as I know.
